version: '3'

services:
  postgres:
    container_name: online_school_pg
    image: postgres
    # build:
    #   context: ./db
    #   dockerfile: ./db/Dockerfile
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - .env
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ${DB_PATH}/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  bot:
    container_name: ege_bot
    build:
      context: .
      dockerfile: ./telegram/Dockerfile
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    links:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - .env
    volumes:
       - pgadmin:/root/.pgadmin
       - ./build_files/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    links:
      - postgres
    restart: unless-stopped

volumes:
    postgres:
    pgadmin:
